### ISSUE TITLE
Duplicated doc?

### ISSUE THREAD

**Issue by renatobo** [bitmovin/unda#4]
Great initiative.

There are two Word Documents in the repository

- https://github.com/bitmovin/unda/blob/main/Universal%20NDA%20v1.0.docx
- https://github.com/bitmovin/unda/blob/main/Universal%20NDA%20v1.0%20(2).docx

It appears the (2) version has no material changes (logo on top left changed)

For clarity, one version only should be listed and historical versions are always accessible via repository history or even better tagging.

The actual NDA should link to a specific tag or commit.

**Comment by JShulman-pixel** [comment]
Thanks for bringing this to our attention Renato!

I've removed a duplicate version

**Comment by JShulman-pixel** [comment]
Hello again @renatobo! We've resolved all of your comments in our most recent commit
